name: HTML Proofer

on: [push, pull_request]

jobs:
  Validate_HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: npm ci
        run: npm ci
      - name: npm build
        run: npm run build
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./docs/.vuepress/dist"
          arguments: '--url-ignore "/(docs/edit/master)/" --check-html'
